name: electric_digital_sketch
description: "A offline first package to draw electrical network items"
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: ^2.1.0
  simple_painter: ^1.4.0
  universal_io: ^2.3.1
  tabler_icons_plus: ^3.44.0
  collection: ^1.19.1
  mb_color_picker: ^0.0.2
  electric_shapes: ^1.0.10
  geolocator: ^14.0.2
  file_selector: ^1.1.0
  share_plus: ^11.1.0

dev_dependencies:
  file_selector_platform_interface: ^2.7.0
  geolocator_platform_interface: ^4.2.6
  very_good_analysis: ^10.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
